services:
  - type: web
    name: flowbit-vanna-ai
    env: python
    runtime: python-3.12.7
    region: oregon
    plan: free
    rootDir: vanna
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: mixtral-8x7b-32768
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
    healthCheckPath: /health

